# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 15:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='priced',
            new_name='num_of_dishes',
        ),
        migrations.AlterField(
            model_name='order',
            name='consists_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakaz.Dish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='made_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 15, 51, 57, 893097, tzinfo=utc)),
        ),
    ]
