# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0002_auto_20170724_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='made_on',
            field=models.DateTimeField(),
        ),
    ]
