# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0003_auto_20170724_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='consists_of',
        ),
        migrations.AddField(
            model_name='order',
            name='consists_of',
            field=models.ManyToManyField(to='zakaz.Dish'),
        ),
    ]
